# Asignment 1

![Assignment 1](assn1.png)


## Equations

### Gaussian function

![gaussian](gauss.png)

### Laplacian of gaussian function

![log](log.png)


In [28]:
import cv2
from kernels import gaussian_blurr_kernel, laplacian_of_gaussian_kernel, gaussian_derivative_kernel_first
from utils import convolve

## Smoothing Kernel

 - Gaussian kernel of **size 5x5** and **sigma = 1**

In [29]:
sigma = 1
m = 5
kernel_g = gaussian_blurr_kernel(m, sigma)
print('Gaussian Blur Kernel:\n', kernel_g)

Gaussian Blur Kernel:
 [[0.00296902 0.01330621 0.02193823 0.01330621 0.00296902]
 [0.01330621 0.0596343  0.09832034 0.0596343  0.01330621]
 [0.02193823 0.09832034 0.16210282 0.09832034 0.02193823]
 [0.01330621 0.0596343  0.09832034 0.0596343  0.01330621]
 [0.00296902 0.01330621 0.02193823 0.01330621 0.00296902]]


## Read Image in Grayscale

In [30]:
img_bw = cv2.imread('./Lena.jpg', cv2.IMREAD_GRAYSCALE)
cv2.imshow('Original Image (B&W)', img_bw)

cv2.waitKey(0)
cv2.destroyAllWindows()

## Operate on image

 - Add padding to image
 - Apply convolution
 - Normalize the output
 - Remove padding

### Gaussian Blurr

In [31]:
import numpy as np
img_bordered, img_conv, img_norm, img_res = convolve(img_bw, kernel_g)

cv2.imshow('Image with Border', img_bordered)
cv2.imshow('Gaussian Convolved Image', img_conv)
cv2.imshow('Normalized Gaussian Convolved Image', img_norm)
cv2.imshow('Result of Gaussian Blurred Image', img_res)

cv2.waitKey(0)
cv2.destroyAllWindows()

## Sharpening Kernel

 - Laplacian of Gaussian kernel of **size 7x7** and **sigma = 1**

In [32]:
n = 7
sigma = 1
kernel_log = laplacian_of_gaussian_kernel(n, sigma)
print('Laplacian of Gaussian Kernel:\n', kernel_log)

Laplacian of Gaussian Kernel:
 [[ 3.14260484e-04  2.63207755e-03  8.57902039e-03  1.23763615e-02
   8.57902039e-03  2.63207755e-03  3.14260484e-04]
 [ 2.63207755e-03  1.74901467e-02  3.91926989e-02  4.30785604e-02
   3.91926989e-02  1.74901467e-02  2.63207755e-03]
 [ 8.57902039e-03  3.91926989e-02  0.00000000e+00 -9.65323523e-02
   0.00000000e+00  3.91926989e-02  8.57902039e-03]
 [ 1.23763615e-02  4.30785604e-02 -9.65323523e-02 -3.18309873e-01
  -9.65323523e-02  4.30785604e-02  1.23763615e-02]
 [ 8.57902039e-03  3.91926989e-02  0.00000000e+00 -9.65323523e-02
   0.00000000e+00  3.91926989e-02  8.57902039e-03]
 [ 2.63207755e-03  1.74901467e-02  3.91926989e-02  4.30785604e-02
   3.91926989e-02  1.74901467e-02  2.63207755e-03]
 [ 3.14260484e-04  2.63207755e-03  8.57902039e-03  1.23763615e-02
   8.57902039e-03  2.63207755e-03  3.14260484e-04]]


# Sharpening using Gaussian Differential kernel

- kernel size **7x7**
- sigma = 1

In [33]:
ksz = 7
sigma3 = 1
kx, ky = gaussian_derivative_kernel_first(ksz, sigma3)

In [34]:
_, img_x_gauss, _, _ = convolve(img_bw, kx)
_, img_y_gauss, _, _ = convolve(img_bw, ky)

grad_mag = cv2.magnitude(img_x_gauss, img_y_gauss)
grad_mag_norm = np.round(cv2.normalize(grad_mag, None, 0, 255, cv2.NORM_MINMAX)).astype(np.uint8)

In [35]:
cv2.imshow('Gaussian Derivative X', img_x_gauss)
cv2.imshow('Gaussian Derivative Y', img_y_gauss)
cv2.imshow('Gradient Magnitude', grad_mag_norm)

cv2.waitKey(0)
cv2.destroyAllWindows()

## Sharpening using LoG

In [36]:
img_bordered_2, img_conv_2, img_norm_2, img_res_2 = convolve(img_bw, kernel_log)

cv2.imshow('Image with Border', img_bordered_2)
cv2.imshow('LoG Convolved Image', img_conv_2)
cv2.imshow('Normalized LoG Convolved Image', img_norm_2)
cv2.imshow('Result of LoG Sharpened Image', img_res_2)

cv2.waitKey(0)
cv2.destroyAllWindows()

# Use the LoG Convolution result as a mask and use it to sharpen the original image

In [37]:
k = 5 # Masking factor

mask = cv2.subtract(img_bw, img_res)
img_sharp = cv2.add(img_bw, mask * k)

cv2.imshow('Original Grayscale Image', img_bw)
cv2.imshow('Blurr filter', img_res)
cv2.imshow('Sharpening filter', img_res_2)
cv2.imshow('Mask', mask)
cv2.imshow('Sharpened Image', img_sharp)

cv2.waitKey(0)
cv2.destroyAllWindows()