# Assignment 2

![Assignment 2](assn2.png)

In [1]:
import cv2
import numpy as np
from kernels import gaussian_blurr_kernel, laplacian_of_gaussian_kernel
from utils import convolve

## Read image in BGR

In [2]:
img_bgr = cv2.imread('./Lena.jpg', cv2.IMREAD_COLOR)

cv2.imshow('Original Image', img_bgr)

cv2.waitKey(0)
cv2.destroyAllWindows()

## Split the image into its color channels

In [3]:
img_b, img_g, img_r = cv2.split(img_bgr)

cv2.imshow('Blue Channel', img_b)
cv2.imshow('Green Channel', img_g)
cv2.imshow('Red Channel', img_r)

cv2.waitKey(0)
cv2.destroyAllWindows()

## Showing different channels in their colors

In [4]:
b = np.zeros_like(img_bgr)
g = np.zeros_like(img_bgr)
r = np.zeros_like(img_bgr)

b[:, :, 0] = img_b
g[:, :, 1] = img_g
r[:, :, 2] = img_r

cv2.imshow('Reconstructed Blue Channel', b)
cv2.imshow('Reconstructed Green Channel', g)
cv2.imshow('Reconstructed Red Channel', r)

cv2.waitKey(0)
cv2.destroyAllWindows()

## Define Smoothing filter kernel

 - Gaussian kernel of **size 5x5** and **sigma = 1**


In [5]:
sigma = 1
m = 5
kernel_g = gaussian_blurr_kernel(m, sigma)
print("Gaussian Kernel:\n", kernel_g)

Gaussian Kernel:
 [[0.00296902 0.01330621 0.02193823 0.01330621 0.00296902]
 [0.01330621 0.0596343  0.09832034 0.0596343  0.01330621]
 [0.02193823 0.09832034 0.16210282 0.09832034 0.02193823]
 [0.01330621 0.0596343  0.09832034 0.0596343  0.01330621]
 [0.00296902 0.01330621 0.02193823 0.01330621 0.00296902]]


## Apply Blurr filter on each channel

In [6]:
_, _, _, img_b_blurred = convolve(img_b, kernel_g)
_, _, _, img_g_blurred = convolve(img_g, kernel_g)
_, _, _, img_r_blurred = convolve(img_r, kernel_g)

cv2.imshow('Blurred Blue Channel', img_b_blurred)
cv2.imshow('Blurred Green Channel', img_g_blurred)
cv2.imshow('Blurred Red Channel', img_r_blurred)

cv2.waitKey(0)
cv2.destroyAllWindows()

## Merge the filtered channels and normalize to get the final result

In [7]:
img_blurred_merged = cv2.merge((img_b_blurred, img_g_blurred, img_r_blurred))
img_blurred = cv2.normalize(img_blurred_merged, None, 0, 255, cv2.NORM_MINMAX)

cv2.imshow('Blurred Merged Image', img_blurred_merged)
cv2.imshow('Blurred BGR Image', img_blurred)
cv2.waitKey(0)
cv2.destroyAllWindows()

Repeat the rpocess and get Log Filtered Image

In [8]:
n = 7
sigma2 = 1
kernel_log = laplacian_of_gaussian_kernel(n, sigma2)

print("Laplacian of Gaussian Kernel:\n", kernel_log)

Laplacian of Gaussian Kernel:
 [[ 3.14260484e-04  2.63207755e-03  8.57902039e-03  1.23763615e-02
   8.57902039e-03  2.63207755e-03  3.14260484e-04]
 [ 2.63207755e-03  1.74901467e-02  3.91926989e-02  4.30785604e-02
   3.91926989e-02  1.74901467e-02  2.63207755e-03]
 [ 8.57902039e-03  3.91926989e-02  0.00000000e+00 -9.65323523e-02
   0.00000000e+00  3.91926989e-02  8.57902039e-03]
 [ 1.23763615e-02  4.30785604e-02 -9.65323523e-02 -3.18309873e-01
  -9.65323523e-02  4.30785604e-02  1.23763615e-02]
 [ 8.57902039e-03  3.91926989e-02  0.00000000e+00 -9.65323523e-02
   0.00000000e+00  3.91926989e-02  8.57902039e-03]
 [ 2.63207755e-03  1.74901467e-02  3.91926989e-02  4.30785604e-02
   3.91926989e-02  1.74901467e-02  2.63207755e-03]
 [ 3.14260484e-04  2.63207755e-03  8.57902039e-03  1.23763615e-02
   8.57902039e-03  2.63207755e-03  3.14260484e-04]]


In [9]:
_, _, _, img_b_log = convolve(img_b, kernel_log)
_, _, _, img_g_log = convolve(img_g, kernel_log)
_, _, _, img_r_log = convolve(img_r, kernel_log)

cv2.imshow('LoG Blue Channel', img_b_log)
cv2.imshow('LoG Green Channel', img_g_log)
cv2.imshow('LoG Red Channel', img_r_log)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
img_log_merged = cv2.merge((img_b_log, img_g_log, img_r_log))
img_log = cv2.normalize(img_log_merged, None, 0, 255, cv2.NORM_MINMAX)

cv2.imshow('Original Image', img_bgr)
cv2.imshow('LoG Merged Image', img_log_merged)
cv2.imshow('LoG BGR Image', img_log)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Convert the image into HSV

In [11]:
img_hsv = cv2.cvtColor(img_blurred, cv2.COLOR_BGR2HSV)

cv2.imshow('HSV Image', img_hsv)

cv2.waitKey(0)
cv2.destroyAllWindows()

## Split the HSV image

In [12]:
img_h, img_s, img_v = cv2.split(img_hsv)

cv2.imshow('Hue Channel', img_h)
cv2.imshow('Saturation Channel', img_s)
cv2.imshow('Value Channel', img_v)

cv2.waitKey(0)
cv2.destroyAllWindows()

## Use the same convolution operations on the HSV channels

In [13]:
_, _, _, img_h_blurred = convolve(img_h, kernel_g)
_, _, _, img_s_blurred = convolve(img_s, kernel_g)
_, _, _, img_v_blurred = convolve(img_v, kernel_g)

In [14]:
hsv_merged_blurr = cv2.merge((img_h_blurred, img_s_blurred, img_v_blurred))
hsv_blurred = cv2.normalize(hsv_merged_blurr, None, 0, 255, cv2.NORM_MINMAX)

cv2.imshow('Blurred HSV', hsv_blurred)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [15]:
_, _, _, img_h_log = convolve(img_h, kernel_log)
_, _, _, img_s_log = convolve(img_s, kernel_log)
_, _, _, img_v_log = convolve(img_v, kernel_log)


In [16]:
hsv_log_merged = cv2.merge((img_h_log, img_s_log, img_v_log))
hsv_log = cv2.normalize(hsv_log_merged, None, 0, 255, cv2.NORM_MINMAX)

cv2.imshow('Log Filtered HSV', hsv_log)

cv2.waitKey(0)
cv2.destroyAllWindows()

## Compare the outputs from the two different color mode images

In [17]:
cv2.imshow('Blurred BGR', img_blurred)
cv2.imshow('Blurred HSV', hsv_blurred)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
cv2.imshow('LoG BGR', img_log)
cv2.imshow('LoG HSV', hsv_log)
cv2.waitKey(0)
cv2.destroyAllWindows()